# Generated by Django 2.1.5 on 2019-01-31 22:00

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Brand',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='Ingredient',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('generic_name', models.CharField(blank=True, max_length=255, null=True)),
                ('nutrition_grades', models.CharField(blank=True, max_length=1, null=True)),
                ('bar_code', models.CharField(max_length=20, unique=True)),
                ('fat', models.CharField(blank=True, max_length=5, null=True)),
                ('saturated_fat', models.CharField(blank=True, max_length=5, null=True)),
                ('sugars', models.CharField(blank=True, max_length=5, null=True)),
                ('salt', models.CharField(blank=True, max_length=5, null=True)),
                ('image_url', models.URLField(blank=True, null=True)),
                ('brands', models.ManyToManyField(to='purbeurre.Brand')),
                ('categories', models.ManyToManyField(to='purbeurre.Category')),
                ('ingredients', models.ManyToManyField(to='purbeurre.Ingredient')),
            ],
        ),
        migrations.CreateModel(
            name='ProductSubstituteProduct',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('from_product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='from_product', to='purbeurre.Product')),
                ('to_product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='to_product', to='purbeurre.Product')),
                ('users', models.ManyToManyField(to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Store',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, unique=True)),
            ],
        ),
        migrations.AddField(
            model_name='product',
            name='stores',
            field=models.ManyToManyField(to='purbeurre.Store'),
        ),
        migrations.AddField(
            model_name='product',
            name='substitutes',
            field=models.ManyToManyField(through='purbeurre.ProductSubstituteProduct', to='purbeurre.Product'),
        ),
    ]
